# Configuration file for yamllint.  For documentation, see
# https://yamllint.readthedocs.io/en/stable/configuration.html
---
extends: default

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
