# This action will regenertae generated files on a weekly schedule.
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Update

on:
  # Allow this workflow to be manually triggered.
  workflow_dispatch:

  # Run this once a week on saturday at 9pm UTC.
  schedule:
    - cron: '0 21 * * 6'

permissions:
  contents: read

jobs:
  generate-files:
    permissions:
      contents: write  # for Git to git push
      pull-requests: write  # for Git to create a pull request
    runs-on: ubuntu-latest
    env:
      SPECDIR: ../specification/
      EXTDIR: ../extracted-files/

    steps:
    - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        disable-sudo: true
        egress-policy: audit

    - name: Checkout GEDCOM.io
      uses: actions/checkout@v4
      with:
        path: GEDCOM.io

    - name: Checkout GEDCOM
      uses: actions/checkout@v4
      with:
        repository: FamilySearch/GEDCOM
        path: GEDCOM

    - name: Generate GEDOM-tmp.md
      working-directory: ${{github.workspace}}/GEDCOM/build
      shell: sh
      run: |
        export MD_FILES=$(ls ${{ env.SPECDIR }}gedcom*.md | sort)
        python3 hyperlink.py ${MD_FILES} GEDCOM-tmp.md
        ls -l GEDCOM-tmp.md

    - name: Generate GEDCOM-tmp.html
      working-directory: ${{github.workspace}}/GEDCOM/build
      shell: sh
      run: |
        echo "Ready..."
        echo "SPECDIR: ${SPECDIR}"
        export MODTIME=$(git log -1 --date="format:%_d %B %Y" --format="%ad" -- ${SPECDIR})
        echo "MODTIME: ${MODTIME}"
        export PDARGS="--syntax-definition=gedcom.xml --syntax-definition=gedstruct.xml --syntax-definition=abnf.xml --from=markdown+smart --standalone --css=pandoc.css --template=template.html --toc --number-sections --self-contained --highlight-style=kate --wrap=none"
        echo "PDARGS: ${PDARGS}"
        docker run --rm --volume "`pwd`:/data" pandoc/latex:2.9 GEDCOM-tmp.md -o GEDCOM-tmp.html ${PDARGS} --metadata=date:"${MODTIME}"
        ls -l GEDCOM-tmp.html

    - name: Generate gedcom.html
      working-directory: ${{github.workspace}}/GEDCOM/build
      run: |
        python3 hyperlink-code.py GEDCOM-tmp.html ../specification/gedcom.html
        ls -l ../specification/gedcom.html

    - name: Install weasyprint
      run: |
        python3 -mpip install --user weasyprint==52.5

    - name: Generate gedcom.pdf
      working-directory: ${{github.workspace}}/GEDCOM/build
      run: |
        python3 -mweasyprint ../specification/gedcom.html ../specification/gedcom.pdf
        ls -l ../specification/gedcom.pdf

    - name: Prep GEDCOM.io
      working-directory: ${{github.workspace}}/GEDCOM/build
      run: |
         ls ../../GEDCOM.io
         python3 push_to_gedcomio.py ../../GEDCOM.io

    - name: Create GEDCOM.io Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        path: GEDCOM.io
        commit-message: Update generated files
        title: 'Update generated files'
        body: |
          Update generated files
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: automated pr
        base: master
